apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
  labels:
    app: mi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mi
  template:
    metadata:
      labels:
        app: mi
    spec:
      containers:
      - name: wso2-mi
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: truststore-volume
          mountPath: /home/wso2carbon/client-truststore.jks
          subPath: client-truststore.jks
      volumes:
      - name: truststore-volume
        configMap:
          name: mi-truststore-config
