apiVersion: v1
kind: Service
metadata:
  name: mi-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mi
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
